{
 "title": "Blog",
 "tags": [
  "blog",
  "analytics",
  "application"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "site", "label": "Site", "query": "blog.entazis.dev" }
  ]
 },
 "panels": [
  {
   "title": "Total Visits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(web_page_visits_total{site=\"$site\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Total Article Reads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(web_article_reads_total{site=\"$site\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Visits Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (page) (increase(web_page_visits_total{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "{{page}}"
    }
   ]
  },
  {
   "title": "Article Reads Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (slug, content_type) (increase(web_article_reads_total{site=\"$site\"}[$__rate_interval]))",
     "legendFormat": "{{content_type}} - {{slug}}"
    }
   ]
  }
 ]
}