{
 "title": "NvcHelper",
 "tags": [
  "app",
  "nvc-helper"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Total Visits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(web_page_visits_total{site=\"nvc-helper\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://nvc-helper.entazis.dev/\"}"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://nvc-helper.entazis.dev/\"}) * 1000"
    }
   ]
  },
  {
   "title": "Visits by Page (hourly)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(web_page_visits_total{site=\"nvc-helper\"}[1h])) by (page)",
     "legendFormat": "{{page}}"
    }
   ]
  }
 ]
}